# Test your FastAPI endpoints

GET http://127.0.0.1:8000/api/player/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/title/GM
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/stats/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/games/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/daily/games/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/games/archives/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/games/vitorpereira26/2024/07
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/clubs/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/matches/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/player/tournaments/vitorpereira26
Accept: application/json

###

GET http://127.0.0.1:8000/api/club/tourn/vitorpereira26
Accept: application/json

###